const path = require('path');
const fs = require('fs');
const ROOT = 'F:\\图形塔防';
const config = require(path.join(ROOT, 'src', 'config'));
const lines = [];
lines.push('TOWER_ORDER = ' + config.TOWER_ORDER.join(','));
lines.push('TOWER_STATS keys = ' + Object.keys(config.TOWER_STATS).join(','));
lines.push('ENHANCE_SPECIAL keys = ' + Object.keys(config.ENHANCE_SPECIAL).join(','));
lines.push('TOWER_STATS.graphic = ' + JSON.stringify(config.TOWER_STATS.graphic));
lines.push('TOWER_ORDER 中缺 TOWER_STATS 的 = ' + config.TOWER_ORDER.filter((t) => !config.TOWER_STATS[t]).join(','));
lines.push('TOWER_ORDER 中缺 ENHANCE_SPECIAL 的 = ' + config.TOWER_ORDER.filter((t) => !config.ENHANCE_SPECIAL[t]).join(','));
fs.writeFileSync(path.join(ROOT, '.workbuddy', 'tmp', '_cfg.txt'), lines.join('\n'), 'utf8');
